"""probe-tesla register writer (2026-09-26). Run once, then delete nothing."""
import csv, os, sys

D = os.path.dirname(os.path.abspath(__file__))
os.chdir(D)
E = "https://www.sec.gov/Archives/edgar/data/0001318605/"

SRC = ["source_id","stage","claim_supported","source_title","author_or_publication","source_type",
       "primary_or_secondary","event_date","publication_date","access_date","url","archived_url",
       "tier","evidence_class","confidence","independence_note","relevant_passage","notes"]
NV = "NO_VERBATIM_PASSAGE_RECORDED"
rows = [
 ["S0001","stage1","F01,F02,F04,F06,F07","Tesla Motors Inc final prospectus 424B4 (lineage of S-1 acc 0001193125-10-017054)","Tesla Motors, Inc. / registrant","SEC filing","primary","2010-06-29","2010-06-29","2026-09-26",E+"000119312510149105/d424b4.htm","not archived this pass","1","FACT (as to the statement)","High","same lineage as S0002 and S0003; retrospective corporate self-report for 2003-2004 facts","Tesla Motors, Inc. ... was incorporated in the state of Delaware on July 1, 2003","2,677,451 B held at sources/sec/0001193125-10-149105_d424b4.htm"],
 ["S0002","stage1","F03,F06,F10,F11","Form S-1 registration statement (original)","Tesla Motors, Inc. / registrant","SEC filing","primary","2010-01-29","2010-01-29","2026-09-26",E+"000119312510017054/ds1.htm","not archived this pass","1","FACT (as to the statement)","High","same lineage as S0001; earliest held carrier","Elon Musk has served as our Product Architect since May 2008, our Chief Executive Officer since October 2008 and as Chairman of our board of directors since April 2004","2,362,163 B held; contains NO Tesla-founder label for any person"],
 ["S0003","stage1","F05","Form S-1/A (third amendment) acc 0001193125-10-099603","Tesla Motors, Inc. / registrant","SEC filing","primary","2010-04-29","2010-04-29","2026-09-26",E+"000119312510099603/ds1a.htm","not archived this pass","1","FOUNDER CLAIM (corporate, retrospective)","High","same lineage as S0001/S0002","the perspective and experience he brings as our Chief Executive Officer, one of our founders and our largest stockholder","first held instance of the founder adjective; absent from S0002"],
 ["S0004","stage1","F01","Tesla Motors Inc FY2010 Form 10-K","Tesla, Inc. / registrant; audited statements","SEC filing","primary","2011-03-03","2011-03-03","2026-09-26",E+"000119312511054847/d10k.htm","not archived this pass","1","FACT (as to the statement)","High","same corporate voice as S0001-S0003, different instrument and year","In June 2009, nine months after its commercial introduction","0 hits for founder / co-founder / Tarpenning / arbitrat over 608,382 chars"],
 ["S0005","stage1","F08","Tesla Motors Inc 2011 DEF 14A proxy","Tesla, Inc. board of directors","SEC filing","primary","2011-04-08","2011-04-08","2026-09-26",E+"000119312511092509/ddef14a.htm","not archived this pass","1","FACT (as to the statement)","Medium-High","board-lineage repeat of S0003 wording; not independent of it","as opposed to preferred stock acquired via investment as was the case with Mr. Musk","588,431 B held"],
 ["S0006","stage1","F10","EDGAR submissions slice CIK 1318605 for 2003-01-01 to 2012-12-31","SEC EDGAR registry","regulatory index","primary","2009-04-09","2026-09-26","2026-09-26","https://data.sec.gov/submissions/CIK0001318605.json","held at sources/_index/submissions.csv","1","FACT","High","independent of the registrant narrative (SEC registry enumeration)",NV,"1,750 filings; earliest 2009-04-09 Form D; zero for 2003-2008"],
 ["S0007","stage1","F11","Wayback CDX rows for tesla.com root (4 timestamps)","Internet Archive","web archive index","primary","2002-11-25","2026-09-26","2026-09-26","https://web.archive.org/cdx/search/cdx?url=www.tesla.com","transcript-retained only; see sources/wayback/README_retained_capture_evidence.md","1","FACT (capture index)","Medium","independent of the registrant; captured page content never read",NV,"captures 2002-11-25 / 2003-02-09 / 2003-02-14 pre-date the stated incorporation; 2006-02-09 is a 302"],
 ["S0008","stage1","U.4","Wayback CDX negative artefacts (504 Gateway Time-out; IA Temporarily Offline; 0 B)","Internet Archive","failed retrieval","primary","2026-09-26","2026-09-26","2026-09-26","https://web.archive.org/cdx/search/cdx","held: sources/wayback/cdx_*.json with sidecars","1","UNKNOWN","n/a","n/a",NV,"UNANSWERED not null; this blocked the 2009 joint-statement lookup"],
 ["S0009","stage1","U.3","Internet Archive advancedsearch responses (3 queries) and Google Books volumes feed (2)","IA catalog / Google Books","catalog index","secondary","2015","2026-09-26","2026-09-26","https://archive.org/advancedsearch.php","held: sources/harvest/internet_archive and sources/harvest/google_books","3","LEAD ONLY","Low","catalog metadata only; no page text held; 2015+ retrospective accounts",NV,"6 book items 2015-2018 incl elonmuskteslaspa0000vanc; 2 queries numFound 0"],
 ["S0010","stage1","U.3","Corporate-print search responses (title-scoped numFound 2; creator-scoped 0)","IA corporate_print route","catalog index","secondary","2008","2026-09-26","2026-09-26","https://archive.org/advancedsearch.php","held: sources/harvest/corporate_print","3","LEAD ONLY","Low","no text layer fetched; candidates tesla-logo and teslaroadster0000maur",NV,"metadata year 2003 on an Annual-Reports container item is NOT treated as a 2003 document"],
 ["S0011","stage1","F12","CourtListener REST v4 search answers (2 queries)","CourtListener / federal courts","court index","primary","2026-09-26","2026-09-26","2026-09-26","https://www.courtlistener.com/api/rest/v4/search/","held: sources/legal/cl_*.json with sidecars","1","FACT (scope of the registry)","High","independent registry, but federal-only coverage",NV,"no 2003-2010 founding record; California Superior Court out of scope so silence is not absence"],
 ["S0012","stage1","U.2","No document held for the founder-dispute carriers (2009 joint statement; 2008-09 state docket; both sides own statements)","UNKNOWN","not retrieved","UNKNOWN","UNKNOWN","UNTRIED","UNTRIED","UNTRIED","UNTRIED","n/a","UNKNOWN","UNKNOWN","no independent carrier reached this pass",NV,"side-2 carriers named in the dossier; highest-value unwritten objects (Untried U-1 to U-3)"],
]
with open("sources.csv","w",encoding="utf-8",newline="") as f:
    w = csv.writer(f, lineterminator="\n"); w.writerow(SRC); w.writerows(rows)

CON = ["company","stage","conflict_id","section","claim_a","claim_a_source","claim_a_date","claim_b",
       "claim_b_source","claim_b_date","why_they_differ","evidence_weight",
       "best_supported_interpretation","residual_uncertainty","confidence"]
con = [
 ["tesla","stage1","U.1","Founder-attribution question; Boundaries","Tesla began 2003-07-01 (Delaware incorporation)","S0001/S0002/S0004 (one lineage)","2010-06-29","The operative beginning is the 2004 financing-and-hire layer","S0002 (same lineage)","2010-01-29","Legal-entity inception vs first functioning moment are different events needed for different purposes","both carried by the same single corporate voice; zero external corroboration","Stage 1 opens 2003-07-01 as an entity fact; the 2004 layer is a later person-level fact, ordered not alternative","whether a functioning team existed 2003-07-01 to 2004-03","High on dates, Low on the meaning of the gap"],
 ["tesla","stage1","U.2","Founder-attribution question; Conflicts","Musk is one of our founders","S0003 first held instance; repeated S0001/S0005","2010-04-29","Musk documented relationship starts April 2004 and his equity was investment-acquired","S0002; S0005","2010-01-29","A characterisation added mid-registration vs the dating and capital structure stated in the same documents","A and B are not independent; a company retrospective self-description cannot corroborate an attribution claim","the same instrument applies the founder adjective, dates the first role to 2004-04 and calls the equity purchased; it does not reconcile them; NOT averaged","what Musk did between 2001 and 2004-04","High on the conflict; UNKNOWN on the underlying question"],
 ["tesla","stage1","U.3","Conflicts","Early officers are described only as former officer and director, never as founders","S0002/S0001; absent from S0004","2010-01-29","An external account treats at least one of them as founder or co-founder","not held (S0012; S0009 lead only)","UNKNOWN","Genre difference: an issuer lists offices, a biography narrates origins","side A held and dated; side B asserted by the brief but unverified this pass","corporate silence is a drafting fact and must not be upgraded into evidence against anyone","complete, on side B","High (A); UNKNOWN (B unheld)"],
 ["tesla","stage1","U.4","Family b web; Conflicts","tesla.com has 200 status captures from 2002-11-25","S0007","2002-11-25","Tesla Motors Inc came into existence 2003-07-01","S0001/S0004","2010-06-29","A capture timestamp indexes a URL not an owner; the domain pre-existed its namesake","both Tier-1 in kind and, once the object is identified, not actually in conflict","earliest-capture evidence must be checked against the incorporation date; here it fails that check","when the entity first placed its own site on the domain","High on both claims and on the resolution rule"],
 ["tesla","stage1","U.5","Boundaries","Roadster deliveries began in early 2008","S0001/S0002","2010-06-29","Commercial introduction about nine months before June 2009 (implies 2008-09)","S0004","2011-03-03","Likely first hand-built deliveries vs a declared commercial-introduction milestone, but the corpus does not say so","equal weight and not independent (same registrant)","Stage 2/3 edge is 2008 with the quarter UNKNOWN; the two-quarter spread is preserved","exact date of the first production Roadster delivery","Medium on 2008; Low on sub-year"],
 ["tesla","stage1","U.6","Founder-attribution question; Conflicts","Fortune 2026 flags Tesla Founder-is-CEO = yes","brief framing; no document held","2026","The earliest dated corporate record gives Chairman from 2004-04 and CEO from 2008-10","S0002","2010-01-29","A binary present-day list field resolves by fiat what the record leaves open","a classifier label is never corroboration of a primary record","the flag is an artefact of the dispute and part of why it is now harder to research","how the flag was derived","High on B; n/a on A"],
]
with open("conflicts.csv","w",encoding="utf-8",newline="") as f:
    w = csv.writer(f, lineterminator="\n"); w.writerow(CON); w.writerows(con)

GAP = ["company","stage","gap","why_missing","importance","best_available_evidence","confidence","follow_up_task"]
gap = [
 ["tesla","stage1","No independent (non-corporate) document at all for the 2003-2004 founding period","EDGAR empty for this issuer before 2009-04-09 (S0006); no registry, patent, periodical page-text or court record reached this pass","High","S0006 null enumeration; S0001-S0005 single-lineage dating","UNKNOWN","Untried U-1/U-2/U-4/U-7: Wayback domain sweep plus 2009 joint statement; San Mateo County docket; S-1 exhibit folder (charter and Series A-D purchase agreements); Delaware Division of Corporations and USPTO"],
 ["tesla","stage1","The founder dispute own documents (2008-09 docket, 2009 joint statement, both sides statements) were never held","Archive CDX 504/offline, HathiTrust interstitial, Chronicling America 403, ia_text 0-mined; state court outside CourtListener scope","High","S0008/S0011/S0012 negative artefacts and scope notes","UNKNOWN","Re-run U-1 when the Archive answers; route the docket through a state-court index (U-2); fetch the Vance item text layer with a larger max-mb and record the HTTP status (U-3)"],
 ["tesla","stage1","First-financing dates 2003-2006 UNKNOWN although the share structure is filed","The four held documents carry amounts and share counts but no closing dates; 0 hits for February 2004 (N4)","High","S0001 Series A-D table at 424B4","UNKNOWN","U-4: grab accession 0001193125-10-149105 without --file and read the exhibit index"],
 ["tesla","stage1","Identity of the July 2003 incorporator and first-director slate","Not enumerated in any held instrument","Medium","S0002 role dates only","UNKNOWN","U-4 exhibits; U-7 Delaware entity file"],
 ["tesla","stage1","Zero in-window periodical page text despite two newspaper-scale routes attempted","IA advancedsearch sees catalog metadata not pages; HathiTrust and Chronicling America blocked from this egress","Medium","S0009/S0010 catalog answers; UNANSWERED list in Nulls","UNKNOWN","U-3 per-item fulltext/inside.php against a candidate magazine item; U-8 non-LC press route"],
 ["tesla","stage1","Documentary and auction family entirely untried","No scripted route in tools/ and no calls left in this pass","Medium","none","UNKNOWN","U-6"],
 ["tesla","stage1","Employee, revenue and product counts for 2003-2007 unrecoverable except as 2010 memory","The company had no reporting duty and the archive families that might hold the numbers were unreachable","Medium","S0001: 646 employees at 2010-05-31; USD 147.6M revenue since inception to 2010-03-31; S0004 USD 415.0M losses since inception","Low","Fold any periodical or print find into Stage 1 registers at assembly"],
]
with open("data_gaps.csv","w",encoding="utf-8",newline="") as f:
    w = csv.writer(f, lineterminator="\n"); w.writerow(GAP); w.writerows(gap)

names = ("sources.csv","conflicts.csv","data_gaps.csv")
print("registers:", [(n, sum(1 for _ in open(n, encoding="utf-8")) - 1) for n in names])
d = open(os.path.join(D, "research", "A_chronology_feasibility.md"), encoding="utf-8").read()
print("PENDING left:", d.count("STATUS: PENDING"), "| words:", len(d.split()), "| sections:", d.count("\n## "))
