import csv, io, re, os

p = os.path.join("founders_playbook", "01_companies", "company_011_microsoft",
                 "research", "B1_periodical_records.md")
F = chr(96) * 3
s = io.open(p, encoding="utf-8").read()


def blk(rows):
    o = io.StringIO()
    w = csv.writer(o, lineterminator="\n")
    w.writerows(rows)
    return o.getvalue()


T_H = ["company", "stage", "date_or_range", "event", "actors", "location",
       "source_id", "evidence_class", "confidence", "conflict_ref", "notes"]
T = [
    ["Microsoft", "stage1", "1975", "Company later states it was founded as a partnership in this year",
     "Bill Gates; Paul Allen; Monte Davidoff", "Albuquerque, New Mexico", "D05",
     "RETROSPECTIVE INTERPRETATION", "Medium", "U.3",
     "No contemporaneous 1975 document naming the entity exists in any held byte (N-12/N-13/N-14)"],
    ["Microsoft", "stage1", "1976-01-31",
     "An entity styled Micro-Soft appears in print with Bill Gates signing as General Partner",
     "Bill Gates", "Menlo Park, California (place of publication)", "D01", "FACT", "Medium", "None",
     "Earliest date any held byte carries about this company; masthead read off the file's own face"],
    ["Microsoft", "stage1", "1976-01-31",
     "The company's own letter states its product line, sunk computer time and royalty outcome",
     "Bill Gates", "Albuquerque, New Mexico", "D01", "FOUNDER CLAIM", "Medium", "U.2",
     "One document, one lineage: source of R01-R05"],
    ["Microsoft", "stage1", "1976-02-29", "The club prints a hostile reply to the letter",
     "Homebrew Computer Club members", "Menlo Park, California", "D02",
     "CONTEMPORANEOUS OBSERVATION", "Medium", "None",
     "Reply cites the January letter by volume and issue"],
    ["Microsoft", "stage1", "1976-03-31",
     "A paying customer's published letter fixes a price and a bundling condition",
     "Homebrew Computer Club reader", "Menlo Park, California", "D03",
     "CONTEMPORANEOUS OBSERVATION", "Medium", "U.2",
     "Only in-window price datum found: 75 USD for 8K BASIC"],
    ["Microsoft", "stage1", "1976-04-30", "The dispute is still live in club print",
     "Homebrew Computer Club members", "Menlo Park, California", "D04",
     "CONTEMPORANEOUS OBSERVATION", "Medium", "None",
     "Cites 'HBCC newsletter V2-1', tying the argument back to D01"],
    ["Microsoft", "stage1", "1976-07",
     "BYTE reports the letter circulating across Radio Electronics, PCC, MITS Computer Notes and club bulletins",
     "BYTE (third party)", "Morris Plains, New Jersey", "D06", "CONTEMPORANEOUS OBSERVATION", "Medium",
     "None", "A reprint footprint, not independent corroboration of the letter's content"],
    ["Microsoft", "stage1", "1977-05", "Kilobaud carries an in-page Microsoft product news line",
     "Kilobaud", "Peterborough, New Hampshire", "D07", "CONTEMPORANEOUS OBSERVATION", "Medium", "None",
     "Identical syndicated copy in held BYTE 1977-05/06: one item, three documents (A2 C-7)"],
    ["Microsoft", "stage1", "1977-07", "A third-party BYTE letter uses the hyphenated Micro-Soft form",
     "BYTE reader", "Morris Plains, New Jersey", "D06", "CONTEMPORANEOUS OBSERVATION", "Medium", "None",
     "Not company copy; earliest non-company use of the name form found"],
    ["Microsoft", "stage1", "1979", "Compute! carries multiple in-page Microsoft BASIC references",
     "Compute!", "Peterborough, New Hampshire", "D08", "CONTEMPORANEOUS OBSERVATION", "Medium", "None",
     "Second half of the probe's text: numFound-2, whose other item was annotation-only"],
    ["Microsoft", "stage1", "1980-12",
     "Company print names Microsoft Consumer Products with a Bellevue address and telephone",
     "Microsoft (ad copy)", "Bellevue, Washington", "D09", "FACT", "Medium", "U.4",
     "Stage-1 close document; 134 hit lines, 0 of them hyphenated"],
    ["Microsoft", "stage2", "1981", "Company later states it was incorporated in this year",
     "Microsoft Corporation", "Washington", "D05", "RETROSPECTIVE INTERPRETATION", "Medium", "U.4",
     "Document-boundary candidate for the Stage-1 close"],
    ["Microsoft", "stage2", "catalogue-1982",
     "Paul G. Allen talk transcript on future plans for MSDOS 2.0", "Paul G. Allen", "UNKNOWN", "D10",
     "FOUNDER CLAIM", "Low", "None",
     "No year on its face; house-organ self-narrative; carried from A2 and not re-opened this pass"],
    ["Microsoft", "stage3", "1986-01",
     "Company print names Microsoft Corporation at Bellevue plus eight further national entities",
     "Microsoft (ad copy)",
     "Bellevue; Munich; Sydney; Berks; Ontario; Sollentuna; Paris; Seoul; Tokyo", "D11", "FACT",
     "Medium", "None",
     "Entity family visible in print at the Stage-3 opening; corporate relationships not established"],
    ["Microsoft", "stage3", "1986-01", "BYTE reproduces a company-authored house-organ column",
     "Microsoft Languages Newsletter", "UNKNOWN", "D11", "FACT", "Medium", "None",
     "Self-narrative inside a third-party magazine: one lineage with the ads"],
    ["Microsoft", "stage3", "1987-04", "Third-party print still uses the hyphenated Micro-Soft form",
     "BYTE contributor", "Morris Plains, New Jersey", "D13", "CONTEMPORANEOUS OBSERVATION", "Medium",
     "None", "Read-only on the Dell shelf; 1 hyphenated line of 200 hit lines"],
    ["Microsoft", "stage3", "1988-08",
     "Company print names Microsoft Corporation as owner of MS OS/2 and MS Windows/386",
     "Microsoft (ad copy)", "UNKNOWN", "D12", "FACT", "Medium", "None",
     "254 hit lines over 1,888,699 B"],
]

Q_H = ["company", "stage", "date", "metric", "value", "unit", "source", "source_date",
       "evidence_class", "confidence", "derived_arithmetic", "notes"]
Q = [
    ["Microsoft", "stage1", "1976-01-31", "claimed value of computer time used in development",
     "40000", "USD (nominal; company's valuation basis unstated)", "D01", "1976-01-31",
     "FOUNDER CLAIM", "Medium", "",
     "Printed as an assertion; no rate, hour count or invoice behind it"],
    ["Microsoft", "stage1", "1976-01-31", "claimed paid share of Altair owners", "less than 10",
     "percent of Altair owners", "D01", "1976-01-31", "FOUNDER CLAIM", "Medium", "",
     "The denominator (Altair owners) is itself an uncounted company assertion"],
    ["Microsoft", "stage1", "1976-01-31", "implied royalty return on development time",
     "less than 2", "USD per hour", "D01", "1976-01-31", "DERIVED", "Low",
     "printed conclusion only: royalties received / hours spent; BOTH inputs absent from the document so the division cannot be reproduced",
     "The company's own arithmetic result, not a figure this project can recompute"],
    ["Microsoft", "stage1", "1976-01-31", "claimed duration of initial development", "2", "months",
     "D01", "1976-01-31", "FOUNDER CLAIM", "Medium", "",
     "Printed as 'Though the initial work took only two months'"],
    ["Microsoft", "stage1", "1976-01-31", "persons named in the company's own origin sentence", "3",
     "persons (Gates; Allen; Davidoff)", "D01", "1976-01-31", "FOUNDER CLAIM", "Medium", "",
     "3 named in one document; the entity's headcount is NOT established by it"],
    ["Microsoft", "stage1", "1976-03-31", "listed price of 8K BASIC to a customer", "75",
     "USD (nominal)", "D03", "1976-03-31", "CONTEMPORANEOUS OBSERVATION", "Medium", "",
     "Single third-party source; conditional on owning qualifying hardware"],
    ["Microsoft", "stage1", "1976-01", "start span implied by the company's 'almost a year ago'",
     "c. 1975-02 to 1975-07", "month span", "D01", "1976-01-31", "DERIVED", "Low",
     "1976-01-31 minus 'almost a year' (read as 8-12 months) gives 1975-02 to 1975-06; the phrase is unquantified",
     "Arithmetic on a vague phrase; no single 1975 date may be printed from it"],
    ["Microsoft", "stage1", "1976", "company-name hit lines across held BYTE 1976", "0", "hit lines",
     "D06", "1976-12-31", "DERIVED", "High",
     "sum of grep -ciE 'micro-?soft' over 12 files = 0 (per-file counts all 0); corpus 5,743,636 B",
     "A measurement over held bytes, not a corpus claim"],
    ["Microsoft", "stage1", "1980-12", "company-name hit lines in BYTE December 1980", "134",
     "hit lines", "D09", "1980-12-31", "DERIVED", "High",
     "grep -ciE 'micro-?soft' byte-1980-12.txt (1,669,716 B) = 134; of these grep -ci 'micro-soft' = 0",
     "A2's '136 hits' counted a different unit: see U.5"],
    ["Microsoft", "stage3", "1986-01", "company-name hit lines in BYTE January 1986", "185",
     "hit lines", "D11", "1986-01-31", "DERIVED", "High",
     "grep -ciE 'Micro-?[Ss]oft' byte-magazine-1986-01_djvu.txt (1,850,712 B) = 185",
     "Unverified TLS"],
    ["Microsoft", "stage3", "1988-08", "company-name hit lines in BYTE August 1988", "254",
     "hit lines", "D12", "1988-08-31", "DERIVED", "High",
     "grep -ciE 'Micro-?[Ss]oft' byte-magazine-1988-08_djvu.txt (1,888,699 B) = 254",
     "Unverified TLS"],
    ["Microsoft", "stage1", "1994-02-14", "EDGAR index rows dated before the registrant's filing floor",
     "0", "filings", "D05", "1994-09-27", "DERIVED", "High",
     "count(filingDate < 1994-02-14) = 0 over 4,525 rows parsed from sources/_index/submissions.csv; minimum 1994-02-14",
     "Establishes family (a) as a NULL for 1975-1990, not a conditional null"],
]

C_H = ["company", "stage", "conflict_id", "section", "claim_a", "claim_a_source", "claim_a_date",
       "claim_b", "claim_b_source", "claim_b_date", "why_they_differ", "evidence_weight",
       "best_supported_interpretation", "residual_uncertainty", "confidence"]
C = [
    ["Microsoft", "stage1", "U.1", "Boundaries",
     "hcc0201 reports Altair BASIC availability set for December 17 1975 with delivery January 15 1976",
     "A2_periodical_and_filings_settlement.md, Family c item 1", "2026-09-25",
     "Those two dates in hcc0201 belong to Processor Technology's VDM-1 video display module, a different product in a different column",
     "company_004_apple/sources/ia_homebrew/hcc0201.txt lines 48-54", "1976-01-31",
     "The earlier dossier attached the dates to Altair BASIC by textual proximity; reading the column shows the subject is the VDM-1 and its character-generator supply",
     "The bytes win: the sentence names VDM-1 and Processor Technology Corporation and never names BASIC",
     "RETRACT. hcc0201 contains no Altair BASIC availability or delivery date; the release date is UNKNOWN again",
     "Whether any 1975-76 print carries an Altair BASIC release date: UNTRIED", "High"],
    ["Microsoft", "stage1", "U.2", "Narrative and quantitative",
     "Company: less than 10 percent of all Altair owners have bought BASIC",
     "company_004_apple/sources/ia_homebrew/hcc0201.txt line 93", "1976-01-31",
     "BYTE: more copies of Altair's BASIC have been pirated than have been legally sold",
     "company_004_apple/sources/ia_byte_1976/byte-1976-09.txt line 2039", "1976-09",
     "Both describe unpaid copying but imply different paid fractions (under 10 percent versus under 50 percent)",
     "Neither is a measurement, and BYTE is downstream of the company's own claim, so it cannot corroborate it",
     "Treat the paid fraction as a company assertion with no independent denominator; the hcc0203 reader's 'one of the 10 percent minority' adopts the company's number rather than counting it",
     "True paid fraction and the Altair installed base are UNKNOWN and probably unrecoverable", "Medium"],
    ["Microsoft", "stage1", "U.3", "Boundaries",
     "A filed statement says the company was founded as a partnership in 1975",
     "FY1994 Form 10-K lines 181-182, accession 0000891020-94-000175", "1994-09-27",
     "No document dated in 1975 naming the entity exists anywhere in the held bytes",
     "Homebrew 0109/0110 35,756 B; BYTE 1976 x12 5,743,636 B; Popular Electronics Mar 1975 493,273 B; all 0 hits",
     "2026-09-26",
     "Different evidence classes: one retrospective company self-report versus an absence of contemporary evidence over a bounded sample",
     "The absence is over named bytes only, so it cannot refute 1975; the filing asserts 1975 nineteen years after the fact",
     "1975 stands as the company's own account, corroborated across two independent lineages (1976 letter, 1994 filing) but never documented contemporaneously",
     "A 1975-dated third-party document may exist in unopened 1975 print (Popular Electronics Jul-Dec 1975, Kilobaud 1975): UNTRIED",
     "Medium"],
    ["Microsoft", "stage1", "U.4", "Boundaries", "Stage 1 closes 1980-12-31",
     "A2_periodical_and_filings_settlement.md, Boundaries", "2026-09-25",
     "The company's own filed statement places incorporation in 1981", "FY1994 Form 10-K line 182",
     "1994-09-27",
     "The provisional close was derived from shelf coverage (where the print thins out); the 1981 date is the only in-corpus document naming a legal transition event",
     "The filed statement is the only evidence of an entity-form change; the shelf-derived date is an inference from coverage",
     "Keep Stage 1 = 1975-1980 for continuity, but record that the transition the company itself reports falls just outside the close; if the orchestrator prefers a document-bound stage, 1981 is the defensible cut",
     "Whether 'incorporated in 1981' means a new corporation, a conversion or a re-domicile is UNKNOWN from this sentence",
     "Medium"],
    ["Microsoft", "stage1", "U.5", "Measurement", "BYTE December 1980 carries 136 Microsoft hits",
     "A2_periodical_and_filings_settlement.md, Family c item 4", "2026-09-25",
     "The same file yields 134 matching lines",
     "grep -ciE 'micro-?soft' over company_004_apple/sources/ia_byte_1981/byte-1980-12.txt (1,669,716 B)",
     "2026-09-26", "Unit definition: occurrences versus matching lines",
     "Both are computed over the same bytes; only one unit may enter the register",
     "Adopt the matching-line count (134) as this register's unit and label every count 'hit lines', never 'mentions'",
     "Which invocation produced 136 is unknown; the A2 file is not editable from this pass", "High"],
]

S_H = ["source_id", "stage", "claim_supported", "source_title", "author_or_publication",
       "source_type", "primary_or_secondary", "event_date", "publication_date", "access_date",
       "url", "archived_url", "tier", "evidence_class", "confidence", "independence_note",
       "relevant_passage", "notes"]
U = "UNKNOWN"
S = [
    ["D01", "stage1", "R01, R02, R03, R04, R05", "Homebrew Computer Club Newsletter Vol. 2 No. 1",
     "Homebrew Computer Club (editorial venue); letter text by Bill Gates",
     "periodical, club newsletter", "primary", "1976-01-31", "1976-01-31", "2026-09-26",
     "identifier hcc0201; bytes company_004_apple/sources/ia_homebrew/hcc0201.txt 28,281 B", U, "1",
     "FOUNDER CLAIM", "Medium",
     "ONE lineage for R01-R05. The club is the publisher; the letter is Gates's own text, so the officer title is company-side and the masthead is club-side",
     "Bill Gates / General Partner, Micro-Soft",
     "Company-authored content inside a third-party venue: cite the venue for the fact of publication, the letter for the content of the claim. Unverified TLS"],
    ["D02", "stage1", "R06", "Homebrew Computer Club Newsletter Vol. 2 No. 2",
     "Homebrew Computer Club", "periodical, club newsletter", "primary", "1976-02-29", "1976-02-29",
     "2026-09-26",
     "identifier hcc0202; bytes company_004_apple/sources/ia_homebrew/hcc0202.txt 43,265 B", U, "3",
     "CONTEMPORANEOUS OBSERVATION", "Medium",
     "Independent of D01 as to the reply's content; derivative as to the existence of the January letter",
     "Regarding your Letter of 3 February 1976 Appearing in Homebrew Computer Club Newsletter Vol. 2 No. 1 / You gave it away; none stole it from you",
     "Unverified TLS"],
    ["D03", "stage1", "R07", "Homebrew Computer Club Newsletter Vol. 2 No. 3",
     "Homebrew Computer Club (reader letter addressed to Mr. Gates)", "periodical, club newsletter",
     "primary", "1976-03-31", "1976-03-31", "2026-09-26",
     "identifier hcc0203; bytes company_004_apple/sources/ia_homebrew/hcc0203.txt 23,686 B", U, "3",
     "CONTEMPORANEOUS OBSERVATION", "Medium",
     "Third-party author writing in response to D01: the '10 percent minority' phrasing is D01's number, not an independent count",
     "I have no objection to legitimately paying $75 for 8K BASIC, or to being required to purchase suitable hardware in order to qualify for that price",
     "Only in-window price datum found. Unverified TLS"],
    ["D04", "stage1", "R06", "Homebrew Computer Club Newsletter Vol. 2 No. 4",
     "Homebrew Computer Club", "periodical, club newsletter", "primary", "1976-04-30", "1976-04-30",
     "2026-09-26",
     "identifier hcc0204; bytes company_004_apple/sources/ia_homebrew/hcc0204.txt 30,810 B", U, "3",
     "CONTEMPORANEOUS OBSERVATION", "Medium",
     "Independent club member, explicitly citing 'HBCC newsletter V2-1'",
     "since Mr. Bill Gates claims that he did not get payed [sic] enough and is in the mood of calling people thieves",
     "Unverified TLS"],
    ["D05", "stage1", "R08, U.3, U.4",
     "Form 10-K, Microsoft Corporation, accession 0000891020-94-000175",
     "Microsoft Corporation / SEC EDGAR", "regulatory filing", "primary", "1994-09-27", "1994-09-27",
     "2026-09-26",
     "https://www.sec.gov/Archives/edgar/data/0000789019/000089102094000175/0000891020-94-000175.txt",
     "same URL; EDGAR is itself the archive; sha1 recorded in the .meta.json sidecar", "1",
     "RETROSPECTIVE INTERPRETATION", "High",
     "Independent lineage from D01: different institution, different date, neither derived from the other",
     "was founded as a partnership in 1975 and was incorporated in 1981 / From 1975 to 1981, Mr. Gates was a partner with Paul Allen, Microsoft's other founder, in the predecessor partnership",
     "TLS certificate-verified; 442,763 B; RETROSPECTIVE SOURCE per section 6"],
    ["D06", "stage1", "R09, U.2, naming drift",
     "BYTE July 1976, September 1976 and July 1977", "BYTE / McGraw-Hill", "trade periodical",
     "secondary", "1976-07", "1976-07 / 1976-09 / 1977-07", "2026-09-26",
     "identifiers byte-1976-07, byte-1976-09, byte-1977-07; bytes company_004_apple/sources/ia_byte_1976 487,633 B and 527,921 B, ia_byte_1977 751,638 B",
     U, "3", "CONTEMPORANEOUS OBSERVATION", "Medium",
     "Reprints and references D01's letter: ONE source for the letter's content, an independent source for the fact of its circulation",
     "it now appears that more copies of Altair's BASIC have been pirated than have been legally sold / While the Micro-Soft venture into APL represents a noble undertaking",
     "Unverified TLS"],
    ["D07", "stage1", "1977 product news", "Kilobaud, May 1977", "Kilobaud", "trade periodical",
     "secondary", "1977-05", "1977-05", "2026-09-26",
     "identifier kilobaudmagazine-1977-05; bytes sources/periodicals/kilobaudmagazine-1977-05_djvu.txt 672,171 B",
     U, "3", "CONTEMPORANEOUS OBSERVATION", "Medium",
     "The OSI news line is syndicated: identical copy in held BYTE 1977-05/06, so one item across three documents",
     "OSI 6502 8K BASIC FOR DISK BY MICROSOFT", "De-duplicated before counting (A2 C-7)"],
    ["D08", "stage1", "1979 breadth of BASIC ports", "Compute! Magazine Issue 001, Fall 1979",
     "Compute!", "trade periodical", "secondary", "1979", "1979", "2026-09-26",
     "identifier 1979-Fall-compute-magazine; bytes sources/periodicals/1979-Fall-compute-magazine_djvu.txt 542,112 B",
     U, "3", "CONTEMPORANEOUS OBSERVATION", "Medium", "Independent of MITS and BYTE house copy",
     "versions of Microsoft BASIC (PET, KIM, SYM, etc.)",
     "Second half of the probe's text: numFound-2; this item's hit is real in-page, the other item's was annotation-only"],
    ["D09", "stage1", "Stage-1 close; entity plurality", "BYTE, December 1980",
     "BYTE / McGraw-Hill carrying Microsoft-supplied advertising",
     "trade periodical carrying company print", "primary", "1980-12", "1980-12", "2026-09-26",
     "identifier byte-magazine-1980-12; bytes company_004_apple/sources/ia_byte_1981/byte-1980-12.txt 1,669,716 B",
     U, "3", "FACT", "Medium",
     "Ad copy is company-authored: self-narrative, not third-party observation",
     "MICROSOFT Consumer Products, 400 108th Ave. N.E., Suite 200, Bellevue, WA 98004. (206) 454-1315.",
     "134 hit lines, 0 hyphenated. Unverified TLS"],
    ["D10", "stage2", "Allen product statement",
     "MS DOS 2.0 / Future plans for MSDOS, by Paul G. Allen", "Paul G. Allen",
     "company print, talk transcript (house organ)", "primary", "UNKNOWN", "1982 (catalogue year only)",
     "2026-09-25",
     "identifier MSDOS2FuturePlansForMSDOSByPaulAllen; bytes sources/periodicals/MSDOS2FuturePlansForMSDOSByPaulAllen_djvu.txt 13,639 B",
     U, "1", "FOUNDER CLAIM", "Low",
     "Named principal speaking as 'we' about the company's own products: self-narrative, one lineage",
     "Over the last seven years, Microsoft has ported its software products to over fifty different operating system environments",
     "No year on its face (A2 C-8). Not re-opened this pass: carried, not newly verified"],
    ["D11", "stage3", "S3-1, S3-2", "BYTE, January 1986, Volume 11 Number 1",
     "BYTE / McGraw-Hill carrying Microsoft-supplied advertising and a company column",
     "trade periodical carrying company print", "primary", "1986-01", "1986-01", "2026-09-26",
     "identifier byte-magazine-1986-01; bytes sources/periodicals/byte-magazine-1986-01_djvu.txt 1,850,712 B",
     U, "3", "FACT", "Medium",
     "The Microsoft Languages Newsletter column is a company house organ reproduced in a third-party magazine: ONE lineage with the advertisements in the same issue",
     "Microsoft Corporation / Bellevue, Washington USA; The IBM C compiler is a repackaging of the Microsoft C Compiler",
     "Masthead read off the file's face. Unverified TLS"],
    ["D12", "stage3", "S3-4", "BYTE, August 1988",
     "BYTE / McGraw-Hill carrying Microsoft-supplied advertising",
     "trade periodical carrying company print", "primary", "1988-08", "1988-08", "2026-09-26",
     "identifier byte-magazine-1988-08; bytes sources/periodicals/byte-magazine-1988-08_djvu.txt 1,888,699 B",
     U, "3", "FACT", "Medium", "Company copy",
     "trademarks of Microsoft Corporation. MS OS/2 and MS Windows/386 are products of Microsoft",
     "254 hit lines. Unverified TLS"],
    ["D13", "stage3", "naming drift to 1987", "BYTE, April 1987", "BYTE / McGraw-Hill",
     "trade periodical", "secondary", "1987-04", "1987-04", "2026-09-26",
     "identifier byte-magazine-1987-04; bytes company_041_dell/sources/periodicals/byte-magazine-1987-04_djvu.txt 1,769,686 B (read-only on a sibling company's shelf)",
     U, "3", "CONTEMPORANEOUS OBSERVATION", "Medium",
     "Third-party venue, third-party author: independent of company print", "Watch out Micro-Soft.",
     "1 hyphenated line of 200 hit lines. Nothing copied or moved"],
]

G_H = ["company", "stage", "gap", "why_missing", "importance", "best_available_evidence",
       "confidence", "follow_up_task"]
G = [
    ["Microsoft", "stage1",
     "Whether Micro-Soft was a partnership as a matter of law, and on what terms",
     "No partnership instrument, registry entry or court record exists in any held byte; family (a) is floored at 1994-02-14 and family (e) is UNTRIED",
     "High",
     "'General Partner, Micro-Soft' in 1976 company print (D01) plus 'founded as a partnership in 1975' in a 1994 filing (D05)",
     "Medium",
     "Family (e): search auction and museum holdings for a 1975-1977 Micro-Soft partnership document, licence or cheque; and New Mexico Secretary of State records (0 calls this session)"],
    ["Microsoft", "stage1", "Any document DATED in 1975 that names the company",
     "Zero hits over 6,272,665 B of bytes dated 1975 or covering it (N-12/N-13/N-14); MITS's own house organ is not held at all",
     "High", "The company's own retrospective statements only (D01, D05)", "Low",
     "Harvest MITS Computer Notes 1975-1976 and People's Computer Company March-April 1976: both are NAMED as carriers of the letter by D06, so their existence is evidenced and their bytes are reachable"],
    ["Microsoft", "stage1", "Revenue, headcount and customer counts for 1975-1980",
     "No filing exists below 1994-02-14; the creator-scoped annual-report route returned numFound 1 and it is a 1997 manual (N-1); XBRL produced 0 bytes (N-18)",
     "High",
     "Company self-reports in D01: 40,000 USD computer time, under 10 percent paid share, under 2 USD per hour",
     "Low",
     "Search Kilobaud and BYTE 1978-1980 for a software-house revenue survey or a MITS royalty report; Chronicling America for Albuquerque business records"],
    ["Microsoft", "stage1", "Altair BASIC release date and the MITS licence terms",
     "The only candidate date in hcc0201 is RETRACTED by U.1 (it belongs to Processor Technology's VDM-1); MITS print is not held",
     "High", "D01's 'almost a year ago' and D06's third-party phrasing 'Altair's BASIC'", "Low",
     "Grep Popular Electronics July-December 1975 and any surviving Computer Notes for licence and royalty language; re-open hcc0201 in full rather than by proximity"],
    ["Microsoft", "stage2",
     "Date of the Allen MSDOS-2.0 talk and what 'over the last seven years' counts",
     "The 13,639 B layer carries no year on its face; the 1982 is a catalogue field only", "Medium",
     "D10 plus A2 conflict C-8", "Low",
     "Re-open the layer for a conference name or internal date; cross-check against 1983-1984 product print"],
    ["Microsoft", "stage3", "Document coverage for 1982-1985 and 1989-1990",
     "No layer in those spans is held on any shelf this session read", "Medium",
     "BYTE 1986-01 and 1988-08 (D11/D12) plus the Dell-shelf 1987-04, 1988-03, 1988-10 and 1988-12",
     "Medium",
     "Harvest BYTE, Kilobaud, PC Magazine and InfoWorld for 1982-1985 and 1989-1990; the probe's inventoried-but-unmined 159 BYTE items 1986-89 and 57 PC Magazine items remain UNTRIED"],
    ["Microsoft", "stage3",
     "Whether anything in 1986-1990 print or filings narrates a public offering",
     "Zero hits for offering, IPO or shareholder over 3,739,411 B of Stage-3 bytes, and EDGAR's floor post-dates the stage by eight years",
     "High",
     "D05, filed 1994-09-27, is the earliest company-authored text available on any listing-era subject",
     "Low",
     "Run sec_intake facts for 1994-1999 (0 bytes produced this session) and read the FY1994 10-K financial statements; do NOT pull 1994 text backwards to stand in for 1986-1990"],
    ["Microsoft", "stage1", "Founder pre-history before 1976-01-31",
     "The Traf-O-Data pattern returns 0 hits across every held text layer (N-15), and no byte dated before 1976-01-31 names either founder",
     "Medium", "None in-window: only retrospectives", "Low",
     "Family (e) plus HathiTrust full-text for Traf-O-Data and 1974-1975 Albuquerque trade print"],
]

sets = [(T_H, T), (Q_H, Q), (C_H, C), (S_H, S), (G_H, G)]
blocks = re.findall(F + "csv\n(.*?)" + F, s, re.S)
assert len(blocks) == 5, len(blocks)
for (h, rows), b in zip(sets, blocks):
    s = s.replace(F + "csv\n" + b + F, F + "csv\n" + blk([h] + rows) + F, 1)
io.open(p, "w", encoding="utf-8", newline="\n").write(s)
print("rewrote 5 blocks; row counts:", [len(r) for _, r in sets])
